version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_jpa_relationship
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: db_jpa_relationship
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      TZ: America/Lima
    ports:
      - "3310:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d # opcional si quieres scripts .sql al iniciar
volumes:
  mysql_data:
